[project]
name = "wagtail-websockets"
version = "0.1.2"
description = "Wagtail admin integration with Django Channels"
authors = [ { name = "Michael Hearn", email = "git@mikehearn.net" } ]
requires-python = ">=3.8"
dependencies = [
    "channels>=3",
    "django>=4.2",
    "channels_redis>=3"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
